version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: hayyak_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hayyak_db
      MYSQL_USER: hayyak
      MYSQL_PASSWORD: hayyak123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: hayyak_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: hayyak_backend
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - ./backend/.env
    environment:
      STATIC_URL: "/static/"
      MEDIA_URL: "/media/"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  mysql_data: