const ENV = {
  API_URL: import.meta.env.VITE_API_URL || "http://localhost:8000/api/v1",
  API_TIMEOUT: import.meta.env.VITE_API_TIMEOUT || 30000,
  NODE_ENV: import.meta.env.MODE || "development",
  IS_PRODUCTION: import.meta.env.PROD,
  IS_DEVELOPMENT: import.meta.env.DEV,
  ENABLE_MOCK_DATA: import.meta.env.VITE_ENABLE_MOCK_DATA === "true",
  ENABLE_LOGGING: import.meta.env.VITE_ENABLE_LOGGING !== "false",
  APP_NAME: "Hayyak",
  APP_VERSION: "1.0.0",
  TOKEN_KEY: "access_token",
  REFRESH_TOKEN_KEY: "refresh_token",
  USER_KEY: "user",
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
  REQUEST_TIMEOUT: 30000,
  RETRY_ATTEMPTS: 3,
  RETRY_DELAY: 1000,
  DEFAULT_LATITUDE: 24.7136,
  DEFAULT_LONGITUDE: 46.6753,
  DEFAULT_RADIUS: 5,
  PAYMENT_GATEWAY: import.meta.env.VITE_PAYMENT_GATEWAY || "stripe",
  STRIPE_PUBLIC_KEY: import.meta.env.VITE_STRIPE_PUBLIC_KEY || "",
  MAP_API_KEY: import.meta.env.VITE_MAP_API_KEY || "",
  LOG_LEVEL: import.meta.env.VITE_LOG_LEVEL || "info",
};
export default ENV;
